# Generated by Django 4.1 on 2022-09-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_tag_category_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_tag', to='events.tag'),
            preserve_default=False,
        ),
    ]
