# Generated by Django 4.1 on 2022-09-02 19:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_tag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('category', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
