# Generated by Django 4.1 on 2022-09-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_tag_managers_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_date',
        ),
    ]
