# Generated by Django 4.1 on 2022-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
