# Generated by Django 4.1 on 2022-09-11 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
