# Generated by Django 4.1 on 2022-09-14 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_event_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
