# Generated by Django 4.1 on 2022-10-03 06:53

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_likes_event_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'event_id']),
        ),
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(related_name='event_tag', to='events.tag'),
        ),
    ]
