# Generated by Django 4.1 on 2022-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_name_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='events.tag'),
        ),
    ]
