# Generated by Django 4.1 on 2022-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default='2022-12-10T13:27:00Z'),
            preserve_default=False,
        ),
    ]
