# Generated by Django 4.1 on 2022-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
