# Generated by Django 4.1 on 2022-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_fname_remove_profile_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'Prefer Not To Say')], max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_user',
            field=models.CharField(choices=[('ARTISTS', 'ARTIST'), ('VENUE', 'VENUE'), ('ORGANIZATION', 'ORGANIZATION'), ('EVENT', 'EVENT')], max_length=50, verbose_name='User Category'),
        ),
    ]
