# Generated by Django 4.1 on 2022-10-04 05:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_gender_alter_profile_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_to, verbose_name='Profile'),
        ),
    ]
