types =[
    ('on site','on site'),
    ('remote','remote'),
    ('hybrid','hybrid')
]

county = [
        ('Nairobi', 'Nairobi'),
        ('Mombasa', 'Mombasa'),
        ('Kwale', 'Kwale'),
        ('Kilifi', 'Kilifi'),
        ('Tana River', 'Tana River'),
        ('Lamu', 'Lamu'),
        ('Taita Taveta', 'TaitaTaveta'),
        ('Garissa' ,'Garissa'),
        ('Wajir', 'Wajir'),
        ('Mandera', 'Mandera'),
        ('Marsabit', 'Marsabit'),
        ('Isiolo', 'Isiolo'),
        ('Meru', 'Meru'),
        ('Tharaka Nithi', 'Tharaka Nithi'),
        ('Embu', 'Embu'),
        ('Kitui' ,'Kitui'),
        ('Machakos', 'Machakos'),
        ('Makueni', 'Makueni'),
        ('Nyandarua', 'Nyandarua'),
        ('Nyeri', 'Nyeri'),
        ('Kirinyaga','Kirinyaga'),
        ('Muranga',"Murang'a"),
        ('Kiambu', 'Kiambu'),
        ('Turkana ','Turkana'),
        ('West Pokot',' West Pokot'),
        ('Samburu', 'Samburu'),
        ('Trans Nzoia' ,'Trans Nzoia'),
        ('Uasin Gishu', 'Uasin Gishu'),
        ('Elgeyo Marakwet', 'Elgeyo-Marakwet'),
        ('Nandi' ,'Nandi'),
        ('Baringo', 'Baringo'),
        ('Laikipia' ,'Laikipia'),
        ('Nakuru', 'Nakuru'),
        ('Narok', 'Narok'),
        ('Kajiado', 'Kajiado'),
        ('Kericho', 'Kericho'),
        ('Bomet', 'Bomet'),
        ('Kakamega' ,'Kakamega'),
        ('Vihiga', 'Vihiga'),
        ('Bungoma', 'Bungoma'),
        ('Busia', 'Busia'),
        ('Siaya', 'Siaya'),
        ('Kisumu' ,'Kisumu'),
        ('HomaBay', 'Homa Bay'),
        ('Migori', 'Migori'),
        ('Kisii', 'Kisii'),
        ('Nyamira', 'Nyamira'),
        
    ]