# Generated by Django 4.1 on 2022-11-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='UNPAID', max_length=25),
        ),
    ]
